# Generated by Django 4.1.7 on 2023-05-02 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('age_rating', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(18)])),
                ('duration', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(240)])),
                ('image', models.ImageField(null=True, upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('ticket_type', models.CharField(choices=[('student', 'Student'), ('child', 'Child'), ('adult', 'Adult')], max_length=7)),
                ('quantity', models.IntegerField(default=1)),
                ('ticket_id', models.AutoField(db_column='ticket_id', primary_key=True, serialize=False, unique=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('covid', models.BooleanField(default=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('seatno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
    ]
