# Generated by Django 4.1.7 on 2023-05-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('child_tickets', models.PositiveIntegerField(default=0)),
                ('student_tickets', models.PositiveIntegerField(default=0)),
                ('adult_tickets', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.showing')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adult', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
