# Generated by Django 4.1.7 on 2023-04-01 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_age_rating_alter_movie_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(240)]),
        ),
    ]
