# Generated by Django 4.1.7 on 2023-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_booking_ticketprice_remove_ticket_movie_delete_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
