# Generated by Django 4.1.7 on 2023-04-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_movie_age_rating_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='showing',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movie'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.screen'),
        ),
    ]
