# Generated by Django 4.1.5 on 2023-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
