# Generated by Django 4.1.7 on 2023-05-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
