# Generated by Django 4.1.5 on 2023-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_date_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
