<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-05-02 13:25
=======
# Generated by Django 4.1.7 on 2023-05-02 12:58
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('cinema', '0005_alter_showing_covid'),
=======
        ("cinema", "0005_alter_showing_covid"),
>>>>>>> origin/main
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='showing',
            name='covid',
=======
            model_name="showing",
            name="covid",
>>>>>>> origin/main
            field=models.BooleanField(default=False),
        ),
    ]
