# Generated by Django 4.1.7 on 2023-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_showing_covid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showing",
            name="covid",
            field=models.BooleanField(default=False),
        ),
    ]
