# Generated by Django 4.1.7 on 2023-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
    ]
