# Generated by Django 4.1.7 on 2023-05-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_booking_user'),
        ('cinema', '0008_booking_qr_code'),
    ]

    operations = [
    ]
