# Generated by Django 4.1.5 on 2023-02-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0010_alter_movie_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticket_id",
                    models.PositiveIntegerField(
                        db_column="ticket_id", primary_key=True, serialize=False
                    ),
                ),
                ("ticket_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("ticket_type", models.CharField(default="Customer", max_length=20)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.movie"
                    ),
                ),
            ],
        ),
    ]
