# Generated by Django 4.1.5 on 2023-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_screens_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
