# Generated by Django 4.1.5 on 2023-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_screen_showing_delete_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='screen',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
