# Generated by Django 4.1.5 on 2023-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('ticket_type', models.CharField(choices=[('student', 'Student'), ('child', 'Child'), ('adult', 'Adult')], max_length=7)),
                ('ticket_quantity', models.IntegerField(default=1)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
