# Generated by Django 4.1.5 on 2023-03-23 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Invalid UK Phone Number', regex='^(\\+44|0)\\d{10}$')]),
        ),
    ]
