# Generated by Django 4.1.7 on 2023-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
