# Generated by Django 4.1.7 on 2023-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0003_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_seats', models.IntegerField(default=50)),
                ('available_seats', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
