# Generated by Django 4.1.7 on 2023-03-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0004_screening_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screening',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
    ]
