# Generated by Django 4.1.7 on 2023-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0005_delete_screening_remove_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
